### ISSUE TITLE
It is not really a mistake

### ISSUE THREAD

**Issue by timur87** [eouia/MMM-NotificationTrigger#1]
It is not really a mistake

I just can not get it to work

I have followed all the steps also see the speech icon on the magicmirror but when I say "ok google" nothing happens

can it be related to the fact that I have to run both input and output via usb?

I try it for a long time help would be really good for me

Thank you

**Comment by eouia** [comment]
Ok google is not default howord. You can try with smart mirror, jarvis or snowboy.
If you want to make your custom hotword, go to snowboy.kitt.ai and make your .pmdl with your voice.

**Comment by timur87** [comment]
MMM hotword does not work for me ..

maybe what went wrong in the instructions of you?
should that work on raspberry 3?

**Comment by timur87** [comment]
Oops! the wrong category is MMM-Assistant Mk2

**Comment by eouia** [comment]
Ok, Please ask again in MMM-Hotoword. And I'll close this issue.
