### ISSUE TITLE
Not an actual issue

### ISSUE THREAD

**Issue by himuura** [eouia/MMM-NotificationTrigger#3]
@eouia im trying to figure out what this module does and i don't quite catch the concept (my fault not yours!). Could you please summarize what this module does in practical terms? I understand that it relays information from one module to the other(s), but what does that mean in a practical way? For instance, can i integrate this with the Assistant MK2 and the NetworkScanner to tell me who's home? The Network Scanner module pings the designated IP's that i configure and shows it on the MM screen, either online or offline. For instance, if i ask the assistant "Who's home?" will it read me the online names? Sorry to bother! Great job by the way, i have tested a couple of your modules and they work like a charm, it's truly a wonderful effort!

**Comment by eouia** [comment]
The concept is slightly different with your instance.
Ok, Let's see another example.

`MMM-PIR-Sensor` (https://github.com/paviro/MMM-PIR-Sensor) will emit notification "USER_PRESENCE". By default, this module's purpose is to detect presence of person then it will turn on/off screen.
But you want to use this module to other purpose - Changing page of `MMM-Pages`(https://github.com/edward-shen/MMM-pages). But `MMM-Pages` can understand only `PAGE_CHANGED`. 
If you want to use these two modules to work together, at least one of modules should be modified for that purpose.
However `MMM-NotificationTrigger` can relay notifications from one to another. This module can catch `USER_PRESENCE` notification then emit new notification `PAGE_CHANGED`. No source modifying is needed.

**Comment by himuura** [comment]
Fantastic!! It's now clear as crystal @eouia !! Thank you for your explanation!

**Comment by eouia** [comment]
@himuura 
I read MMM-NetworkScanner and have found it has some notification features.
`occupiedCMD` is that.
So,
if you set like this;
**configuration of MMM-NetworkScanner**
```
occupiedCMD: {notification: 'ASSISTANT_SAY', payload: "One of your family is return home"},
```
MMM-AssistantMk2 will say "One of your family is return home" when registered device is connected.
Unfortunately, MMM-NetworkScanner won't give device info, so unable to distinguish who he is.

If you want to get the voice response of "Who is in the house now", you should make two things;
- gAction for Query "Who is in the house now"
- source modification of MMM-NetworkScanner for give an response for that query.

Anyway, I'll close this issue. Have a nice day or dream wherever you are.
