### ISSUE TITLE
Issue with REMOTE_ACTION

### ISSUE THREAD

**Issue by bolish** [eouia/MMM-NotificationTrigger#4]
Hi,

I'm not managing to get below code working...
I'm sure the parameters are the right ones because I tried to launch the same notification within the explorer with remote control and http:// and it works. (both "ARTICLE_MORE_DETAILS" and "HIDE module 8" works).
I also get no syntax error when launching MM...
So there is a mistake somewhere I can not understand. (maybe in the way I write the payload)
Appreciate your support.

> 		{
			module: "MMM-NotificationTrigger",
			config: {
				useWebhook: false,
				triggers: [
					{
						trigger: "ARTICLE_MORE_DETAILS",
						fires: [
							{		
								fire: "REMOTE_ACTION",
								  payload: {
    									action: "HIDE",
    									module: "module_8_compliments",
									},
							}
							]
					},
					{
						trigger: "ARTICLE_LESS_DETAILS",
						fires: [
							{		
								fire: "REMOTE_ACTION",
								  payload: {
    									action: "SHOW",
    									module: "module_8_compliments",
									},
							}
							]
					}
					]
				}				
		},

**Comment by eouia** [comment]
Which module would receive “REMOTE_ACTION”?

**Comment by bolish** [comment]
Hi, it's supposed to be MMM-Remote-Control, which is able to manage Hide / Show modules.

**Comment by eouia** [comment]
I've updated. Could you test?

**Comment by bolish** [comment]
working like a charm now!
I was convinced the issue was coming from me but seems not!
Perfect, thanks for your reactivity.

**Comment by eouia** [comment]
It was my carelessness. payload should have been a callback function, but someone might not be experienced to programming. So I modified that static payload values could be available instead callback function.
Have a nice day.

**Comment by bolish** [comment]
Ahh OK, you adapted your code for noobs. Anyway, thanks for that and enjoy your day.
