### ISSUE TITLE
Exec Fire Question

### ISSUE THREAD

**Issue by shayfer** [eouia/MMM-NotificationTrigger#7]
Great module! I was curious what I am doing wrong in my code. I am trying to use the Motion Detection from rejas module to fire the screensaver. I have the command right but I am having issues getting the config to work. (I cannot use his module because the TV I have displays a glaring red no signal screen which cannot be changed.) The work around I think could be this module to fire the xscreensaver-command -activate when motion is detected and -deactivate when moition is detected.

Thanks!

{
			module: "MMM-NotificationTrigger",
			config: {
			useWebhook:true,
			triggers:[
		{
			trigger: "motion-detected",
			fires: [
        {
            fire:"MY_COMMAND",
			exec: "xscreensaver-command -deactivate"
        },
        ],
        },
        ]
		}
		},
		{
			trigger: "motion-stopped",
			fires: [
         {
            fire:"MY_COMMAND",
			exec: "xscreensaver-command -activate"
        },
        ],
		},
		]
		}
		},

**Comment by eouia** [comment]
Not sure but it seems getting wrong or missing path for xscreen-command. It might be './xscreen-command ...' or '/some/path/xscreen...' whatever.

**Comment by shayfer** [comment]
thanks for the feedback. The first issue I get is the config will not run. I have to remove it to get the mirror back to running. Second I  just wanted to make sure I had the syntax right for the exec as well. I will google around for the location of xscreensaver but within putty I can just run the command without going to the file location.

**Comment by eouia** [comment]
Well, major problem was, your config had wrong syntax. You should pair open/close brackets.
Second, your **motion-stopped** `trigger` section is located in wrong position. it should be inside of `triggers`.

I think it would work(but not tested really);
```js
{
  module: "MMM-NotificationTrigger",
  config: {
    useWebhook:true,
    triggers:[
      {
        trigger: "motion-detected",
        fires: [
          {
            fire:"MY_COMMAND",
            exec: "xscreensaver-command -deactivate"
          },
        ],
      },
      {
        trigger: "motion-stopped",
        fires: [
          {
            fire:"MY_COMMAND",
            exec: "xscreensaver-command -activate"
          },
        ],
      },
    ]
  }
},
```

**Comment by shayfer** [comment]
Hey thanks for the tips!  The config runs but doesn't activate the screensaver when no motion is detected. Does this happen to have a debug I can check out?

**Comment by eouia** [comment]
executing other shell command or script (by example, play wave file) instead of screensaver?

**Comment by shayfer** [comment]
Do I need to define the MY_COMMAND?  Also thanks I will try to play a wave file good call.

**Comment by eouia** [comment]
no. that is just dummy notification. no module will use that noti(maybe). If you want, change it to whatever you want.

**Comment by shayfer** [comment]
Ok thats what I thought thanks. Still no luck for a wav file or the xscreensaver.  I am trying a different approach and created a activate.sh and deactivate.sh  How would I insert the code? Would this be correct?

{
  module: "MMM-NotificationTrigger",
  config: {
    useWebhook:true,
    triggers:[
      {
        trigger: "motion-detected",
        fires: [
          {
            fire:"MY_COMMAND",
            exec: (payload) => {
            return "/somewhere/my/deactivate.sh " + payload.option
          },
        ],
      },
      {
        trigger: "motion-stopped",
        fires: [
          {
            fire:"MY_COMMAND",
            exec: (payload) => {
            return "/somewhere/my/activates.sh " + payload.option
          },
        ],
      },
    ]
  }
},

**Comment by eouia** [comment]
First, check "motion-detected" and "motion-stopped" are emitted without problem. 
With my test, there is no error at all.

```js
{
  module: "MMM-NotificationTrigger",
  config: {
    useWebhook:true,
    triggers:[
      {
        trigger: "motion-detected",
        fires: [
          {
            fire:"MY_COMMAND",
            exec: "date"
          },
        ],
      },
      {
        trigger: "motion-stopped",
        fires: [
          {
            fire:"MY_COMMAND",
            exec: "pwd"
          },
        ],
      },
    ]
  }
},

```
With this config, I test the notification "motion-detected" and "motion-stopped". On "motion-detected", `date` command will be executed. On "motion-stopped", `pwd` command will be executed.
And the result would print out on log, like this;
<img width="682" alt="ttt1" src="https://user-images.githubusercontent.com/1720610/64381131-c5623280-d032-11e9-8cfb-c95fb0a10b19.png">

**Comment by shayfer** [comment]
Ok will try and run a test and find the log. Does it matter if this notification config comes after the motion-detector in the config?

**Comment by eouia** [comment]
https://github.com/rejas/MMM-MotionDetector
is this the module which are you using? there seems no notification like "motion-detected" and "motion-stopped".
there be only "MOTION_DETECTED" notification with payload. I think you have confusing with how to use that module.

**Comment by shayfer** [comment]
Yes that is the module I am using with this module.

**Comment by eouia** [comment]
I have no idea about that module. its not mine. but you tried to use "motion-detected" notification, so i assumed that notification exists and be valid. but not at all. There was no "motion-detected" notification in that module. so your trial was totally wrong.

**Comment by eouia** [comment]
And in my example of readme, the module was https://github.com/dmcinnes/MMM-Motion-Detection

**Comment by shayfer** [comment]
My bad your right. I was using the rejas and not the dmcinnes.  I can't get the dmcinnes to work for my usb cam but I think that is because it hasn't been updated in awhile.  Thanks for your help!
